version: '3'

services:
  data:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - '5432'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro

  server:
    image: graphile/postgraphile:latest
    depends_on:
      - data
    ports:
      - '5000:5000'
    volumes:
      - ./postgraphilerc.js:/postgraphile/.postgraphilerc.js:ro
